### ISSUE TITLE
useRxDocument type does not support numeric id

### ISSUE THREAD

**Issue by wnz99** [cvara/rxdb-hooks#18]
Hi,

is there a specific reason why `idAttribute` has to be of type `string`?

https://github.com/cvara/rxdb-hooks#userxdocument

I'm fetching a document with the following code: 

```
  const { result: video } = useRxDocument('videos', Number(id), {
    idAttribute: 'id',
    json: true,
  });
```
and TS throws and error.

The `videos` schema has this property:

```
    id: {
      type: 'number',
    },
```

**Comment by cvara** [comment]
`idAttribute` holds the name of an attribute which can only be a string. The type of the `idAttribute` -as in, the type of data that attribute can hold in rxdb- is irrelevant and depends on your schema. 

The TS error has to be caused by something else. Could you share some specifics or -even better- a fiddle?

**Comment by wnz99** [comment]
Apologies, I meant the second argument of the function:

```javascript
function useRxDocument<T>(
	collectionName: string,
	id?: string,
	options?: UseRxDocumentOptions
): RxDocumentRet<T>
```
so `id`

**Comment by cvara** [comment]
Right, this is indeed too restrictive. It ought to also allow the `number` type, which would make it consistent with the types allowed on [indexes in rxdb schemas](https://rxdb.info/rx-schema.html#indexes).
