### ISSUE TITLE
useRxCollection returns null the first time it is called?

### ISSUE THREAD

**Issue by special-character** [cvara/rxdb-hooks#23]
Hello and thanks for the awesome project!

While using `useRxCollection` I found it doesn't return the collection the first time it is called in a particular component for me. Is this by design?

ex:
```
const itemsCollection = useRxCollection('items')
 // ❓ useRxCollection returns null the first time????
  console.log('itemsCollection', itemsCollection)
const query = itemsCollection.find().where('owner').equals(userId)
const { result: items, isFetching: isFetchingItems } = useRxQuery(query)
```

I was expecting `itemsCollection` to get the right owner but it throws an error because the collection is null on the first render of the component. I made sure I did the setup with the provider correctly and used await on `db.addCollections({ items: {...}})`.

I might be messing up somewhere else but figured I could open here to see if anyone else has run into this.

**Comment by cvara** [comment]
Yes, by design `useRxCollection` returns **null** until the collection becomes available so you would have to account for this.

Alternatively, which is what I would recommend, you can use `useRxData` which is a thin wrapper around `useRxQuery` that handles this for you and makes for a more concise syntax.

So your example could be rewritten as follows:

```javascript
const { 
  result: items, 
  isFetching: isFetchingItems 
} = useRxData('items', col => col.find().where('owner').equals(userId));
```

**Comment by special-character** [comment]
Thanks for the response and clarification! I think this is good to close.
